Feat: Added Bulk Edit feature
sparrowapp-dev/sparrow-app pull request #1136
Opened 2024-06-25 11:54 UTC by Abhishek9503

## Description

#1008 
#1009 
In this PR i have added both Bulk Edit and Bulk Paramters feature

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build

## Have you tested locally?

- [ ] 👍 yes
- [ ] 🙅 no, because I am lazy

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md

## Any Known issue?
## Related Story, task & Documents?

2024-06-25 13:30 UTC, Astitva877 commented on src/packages/@app/styles/style.scss
> +  --text-secondary-550 : #{$theme-grey-808080};
please follow the numbering structure here.

2024-06-25 19:12 UTC, itsmdasifraza requested changes

2024-06-25 19:12 UTC, itsmdasifraza commented on src/packages/@app/database/database.ts
> +          },
add migrated tab doc fields here

2024-06-25 19:12 UTC, itsmdasifraza commented on src/packages/@common/types/workspace/request.ts
> +  isBulkEditEnabled: boolean;
not required

2024-06-26 12:59 UTC, Abhishek9503 commented on src/packages/@app/database/database.ts
> +          },
I didn't got your point....

2024-06-26 13:53 UTC, itsmdasifraza commented on src/packages/@common/types/workspace/request.ts
> +
update here also

2024-06-26 14:08 UTC, itsmdasifraza commented on src/packages/@workspaces/features/rest-explorer/layout/RestExplorer.svelte
> +                  ?.isBulkHeader}
```
isBulkEditActive={$tab?.property?.request.state
                  ?.isHeaderBulkEditActive}
```

2024-06-27 09:47 UTC, itsmdasifraza commented
1 comment is still unresolved for "switch generic component"

2024-06-27 11:48 UTC, Abhishek9503 commented
> 1 comment is still unresolved for "switch generic component"

Done

2024-06-27 11:51 UTC, itsmdasifraza approved these changes

2024-06-27 13:11 UTC, gc-codes approved these changes

2024-06-27 13:12 UTC, merged