Fix: fixed UI bugs sprint 2
sparrowapp-dev/sparrow-app pull request #1194
Opened 2024-07-06 17:29 UTC by Abhishek9503

## Description

In this Pr i have solved the bug 
1.[Workspaces & Teams] “No result was found” message is missing in list view- 1188
2.Fixed the colour of scrollbar  in Team and worksapce section also in save request section

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build

## Have you tested locally?

- [ ] 👍 yes
- [ ] 🙅 no, because I am lazy

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md

## Any Known issue?
## Related Story, task & Documents?

2024-07-06 17:30 UTC, pratikshinde590 commented
Please attach the issue link

2024-07-08 11:43 UTC, itsmdasifraza requested changes

2024-07-08 11:43 UTC, itsmdasifraza commented on src/packages/@workspaces/features/save-as-request/layout/SaveAsRequest.svelte
> +  }
color name ???

2024-07-08 11:43 UTC, itsmdasifraza commented on src/packages/@teams/features/recent-workspace/layout/RecentWorkspace.svelte
> +    /* background-color: red; */
comment not required

2024-07-08 11:43 UTC, itsmdasifraza commented on src/packages/@teams/features/recent-apis/layout/RecentApi.svelte
> +    /* background-color: red; */
comment not required

2024-07-08 11:43 UTC, itsmdasifraza commented on src/packages/@workspaces/features/save-as-request/layout/SaveAsRequest.svelte
> +  }
trigger ::webkit with parent

2024-07-09 14:49 UTC, pratikshinde590 commented
Please attach the issue link

2024-07-09 19:18 UTC, itsmdasifraza commented
please use issue hash in commit message ex-
`feat: commit message [#1095]`

2024-07-10 11:51 UTC, Astitva877 commented on src/packages/@app/styles/style.scss
> +  --bg-secondary-330 : #{$theme-grey-333333};
do also add these for icon, border, text

2024-07-11 06:37 UTC, Astitva877 approved these changes

2024-07-11 06:42 UTC, itsmdasifraza approved these changes

2024-07-11 06:42 UTC, merged

2024-07-19 13:34 UTC, pratikshinde590 commented
:tada: This PR is included in version 2.3.0 :tada:

The release is available on [GitHub release](https://github.com/sparrowapp-dev/sparrow-app/releases/tag/v2.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: