Feat: Added Viewing Team Member Popup
sparrowapp-dev/sparrow-app pull request #1214
Opened 2024-07-10 14:38 UTC by Abhishek9503

## Description

#1146 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build

## Have you tested locally?

- [ ] 👍 yes
- [ ] 🙅 no, because I am lazy

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md

## Any Known issue?
## Related Story, task & Documents?

2024-07-11 06:12 UTC, itsmdasifraza requested changes

2024-07-11 06:12 UTC, itsmdasifraza commented on src/packages/@library/ui/modal/Modal.svelte
> +    border-radius: 6px;
comment not required here

2024-07-11 06:12 UTC, itsmdasifraza commented on src/packages/@library/icons/Arrow.svelte
> +</script>
use 24 24 grey

2024-07-11 06:12 UTC, itsmdasifraza commented on src/packages/@library/forms/select/Select.svelte
> +              : "var(--sparrow-text-color)"}
icon color should start with --icon

2024-07-11 06:12 UTC, itsmdasifraza commented on src/packages/@library/forms/select/Select.svelte
> +              : "var(--sparrow-text-color)"}
icon color should start with --icon

2024-07-11 06:13 UTC, itsmdasifraza requested changes

2024-07-11 06:13 UTC, itsmdasifraza commented on src/packages/@library/ui/modal/Modal.svelte
> +    bottom: 0;
class name should be more better

2024-07-11 06:15 UTC, itsmdasifraza commented
use issue hash in comment, please don't leave PR description blank

2024-07-12 06:10 UTC, Abhishek9503 commented on src/packages/@library/ui/modal/Modal.svelte
> +    border-radius: 6px;
Resolved

2024-07-12 06:12 UTC, Abhishek9503 commented on src/packages/@library/icons/Arrow.svelte
> +</script>
Resovled

2024-07-12 06:32 UTC, Abhishek9503 commented on src/packages/@library/ui/modal/Modal.svelte
> +    bottom: 0;
Resolved

2024-07-12 06:32 UTC, Abhishek9503 commented on src/packages/@library/forms/select/Select.svelte
> +              : "var(--sparrow-text-color)"}
Resolved

2024-07-12 06:36 UTC, Abhishek9503 commented on src/packages/@library/forms/select/Select.svelte
> +              : "var(--sparrow-text-color)"}
Resolved

2024-07-12 08:14 UTC, Abhishek9503 commented
> use issue hash in comment, please don't leave PR description blank

Resovled

2024-07-15 08:28 UTC, itsmdasifraza approved these changes

2024-07-15 12:24 UTC, merged