fix: Fixed missing Add Member option in workspace list view [#1278]
sparrowapp-dev/sparrow-app pull request #1353
Opened 2024-07-31 13:22 UTC by Abhishek9503

## Description
#1278 
In this PR i have added the option of add member in dropdown which comes when we click on three dot  on list view of workspace under Teams section.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build

## Have you tested locally?

- [ ] 👍 yes
- [ ] 🙅 no, because I am lazy

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md

## Any Known issue?
## Related Story, task & Documents?

2024-08-01 08:17 UTC, itsmdasifraza approved these changes

2024-08-01 08:22 UTC, Astitva877 commented on src/packages/@teams/common/compopnents/rows/Rows.svelte
> +  export let getWorkspaceDetails;
change these prop name  to onAddMembers

2024-08-01 08:23 UTC, Astitva877 requested changes
change the prop name everywhere

2024-08-01 09:19 UTC, Astitva877 approved these changes

2024-08-01 09:19 UTC, merged

2024-08-02 12:01 UTC, pratikshinde590 commented
:tada: This PR is included in version 2.4.0 :tada:

The release is available on [GitHub release](https://github.com/sparrowapp-dev/sparrow-app/releases/tag/v2.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: