Fix/p1 issues from sprint
sparrowapp-dev/sparrow-app pull request #1424
Opened 2024-08-21 07:07 UTC by isha-dubey

## Description

If this code is merged it will solve the P1 bugs from this sprint , following are there tags -
#1383 
#1359 
#1380 
#1374 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build

## Have you tested locally?

- [ ] 👍 yes
- [ ] 🙅 no, because I am lazy

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md

## Any Known issue?
## Related Story, task & Documents?

2024-08-21 14:09 UTC, itsmdasifraza commented on src/packages/@app/pages/Help/HelpPage.ViewModel.ts
>      return;
handle edge case for undefined version

2024-08-21 14:10 UTC, itsmdasifraza requested changes

2024-08-21 14:10 UTC, itsmdasifraza commented on src/packages/@app/components/App.svelte
> +  });
lets connect for this

2024-08-22 09:31 UTC, Astitva877 approved these changes

2024-08-22 13:14 UTC, itsmdasifraza commented on src/packages/@app/pages/Help/HelpPage.ViewModel.ts
> +    await open(`${LearnMoreURL}/tag/${version}`);
` if (!version) {`
 this will work

2024-08-23 06:26 UTC, itsmdasifraza commented on src/packages/@deprecate/components/text/ComboText.svelte
>      >
ui fix required

2024-08-23 07:17 UTC, itsmdasifraza approved these changes

2024-08-23 07:17 UTC, merged