Mitesh dev2
sparrowapp-dev/sparrow-app pull request #1467
Opened 2024-08-29 11:03 UTC by MiteshDarda

## Description

Issues Addressed (Aug 5 - Aug 9):

Fixes:

	•	Aligned the sparrow icon correctly on the default screen.
	•	Updated the drop-shadow effect for AI suggestions icons.
	•	Adjusted the position of the “(… Generating)” text in the AI chat box.
	•	Improved the hover state of the “Send Message” icon.
	•	Fixed the UI of the document input box.

Features:

	•	In AI chat, replaced the copy icon with a tick icon for 5 seconds after copying.
	•	Added new animations for the appearance and disappearance of the AI chat.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build

## Have you tested locally?

- [ ] 👍 yes
- [ ] 🙅 no, because I am lazy

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md

## Any Known issue?
## Related Story, task & Documents?

2024-08-29 17:10 UTC, itsmdasifraza commented on src/packages/@app/styles/style.scss
>  }
this is not following the existing naming pattern

2024-08-29 17:47 UTC, itsmdasifraza requested changes

2024-08-29 17:47 UTC, itsmdasifraza commented on src/packages/@library/ui/tooltip/Tooltip.svelte
> +    }
cant change `show` variable in library module, this should be handled from the app components only as a props, this variable holds some kind of accessibility for guest user.

2024-08-29 17:47 UTC, itsmdasifraza commented on src/packages/@workspaces/features/chat-bot/assests/Tick.png
tick.png not required lets migrate it to svg

2024-08-29 17:47 UTC, itsmdasifraza commented on src/packages/@workspaces/features/chat-bot/components/chat-item/ChatItem.svelte
> +  import { tick } from "svelte";
import tickIcon from index as used or copy Icon

2024-08-29 17:47 UTC, itsmdasifraza commented on src/packages/@workspaces/features/chat-bot/components/prompt-input/PromptInput.svelte
> +
let make it more descriptive, for example `isSendButtonHovered`

2024-08-29 17:47 UTC, itsmdasifraza commented on src/packages/@workspaces/features/chat-bot/components/prompt-input/PromptInput.svelte
use arrow function, we are following es6 patterns

2024-08-29 17:47 UTC, itsmdasifraza commented on src/packages/@workspaces/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte
> +    placement={"bottom-left"}
guest user can also save, and I think requestUrl has not any dependency to show or hide tooltip
cc: @nagesh953 @Monika-APM @astitva-techdome

2024-08-29 17:47 UTC, itsmdasifraza commented on src/packages/@workspaces/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte
>           style="background-color: {isSave ? 'var(--icon-secondary-550)' : 'var(--bg-secondary-400)'}; color: white;"
api save button cant be dependent on request url or guest user 
cc: @nagesh953 @Monika-APM  @astitva-techdome

2024-08-29 17:47 UTC, itsmdasifraza commented on src/packages/@workspaces/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte
> +          ? "var(--icon-disabled-100)"
color doesnt have any dependency on guest user or request url
cc: @nagesh953 @Monika-APM  @astitva-techdome

2024-08-29 17:47 UTC, itsmdasifraza commented on src/packages/@workspaces/features/rest-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
> +    overflow-y: auto;
lets work on deciding class names, haha

2024-09-02 13:16 UTC, Astitva877 requested changes
Please resolve the merge conflict

2024-09-03 06:22 UTC, itsmdasifraza approved these changes

2024-09-03 06:23 UTC, itsmdasifraza approved these changes

2024-09-03 10:17 UTC, pratikshinde590 commented
Please attach the issue link

2024-09-03 10:34 UTC, Astitva877 approved these changes

2024-09-03 10:35 UTC, merged

2024-09-13 15:32 UTC, pratikshinde590 commented
:tada: This PR is included in version 2.7.0 :tada:

The release is available on [GitHub release](https://github.com/sparrowapp-dev/sparrow-app/releases/tag/v2.7.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: