Feat: Added test flow drag drop functionality
sparrowapp-dev/sparrow-app pull request #1600
Opened 2024-09-20 11:20 UTC by anujnema5

## Description

#1398 
In this pr i have added the functionality of drag and drop in the test flow 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build

## Have you tested locally?

- [ ] 👍 yes
- [ ] 🙅 no, because I am lazy

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md

## Any Known issue?
## Related Story, task & Documents?

2024-09-20 12:32 UTC, Astitva877 commented on src/packages/@workspaces/features/collection-list/components/request/Request.svelte
> +      collection: collection,
from here we don't need to send the collection, it's already available in testflowexplorer

2024-09-20 12:34 UTC, Astitva877 commented on src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte
> +  function drop(event) {
convert this to arrow function

2024-09-20 12:36 UTC, Astitva877 requested changes
Please resolve the requested changes.

2024-09-21 15:12 UTC, itsmdasifraza commented on src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte
> +  let requestId: string;
data type missing

2024-09-21 15:21 UTC, itsmdasifraza commented on src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte
> +    collection = data.collection;
add let

2024-09-25 11:36 UTC, closed without merging