fix: fixed issue in workspace page [#1840]
sparrowapp-dev/sparrow-app pull request #1916
Opened 2024-10-28 12:46 UTC by Abhishek9503

## Description

fix: fixed issue in workspace page [#1840]

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build

## Have you tested locally?

- [ ] 👍 yes
- [ ] 🙅 no, because I am lazy

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

2024-10-30 07:26 UTC, Astitva877 approved these changes

2024-11-01 05:29 UTC, itsmdasifraza requested changes

2024-11-01 05:29 UTC, itsmdasifraza commented on packages/@sparrow-common/src/features/delete-workspace/layout/DeleteWorkspace.svelte
> +    style="font-size: 16px; display:flex; flex-wrap:wrap;"
Not required to change layout

2024-11-04 05:51 UTC, Abhishek9503 commented on packages/@sparrow-common/src/features/delete-workspace/layout/DeleteWorkspace.svelte
> +    style="font-size: 16px; display:flex; flex-wrap:wrap;"
Removed

2024-11-06 09:27 UTC, itsmdasifraza approved these changes

2024-11-06 09:28 UTC, merged

2024-11-08 13:25 UTC, pratikshinde590 commented
:tada: This PR is included in version 2.11.0 :tada:

The release is available on [GitHub release](https://github.com/sparrowapp-dev/sparrow-app/releases/tag/v2.11.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: