refactor: create generic progress bar
sparrowapp-dev/sparrow-app pull request #239
Opened 2024-02-13 13:30 UTC by itsmdasifraza

## Description
create generic progress bar
Fixes issue #141 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build

## Have you tested locally?

- [ ] 👍 yes
- [ ] 🙅 no, because I am lazy

2024-02-13 14:12 UTC, parthdalaltech requested changes

2024-02-13 14:12 UTC, parthdalaltech commented on src/lib/components/Transition/progress-bar/ProgressBar.svelte
> +    position: fixed;
class p-fixed check from bootstrap

2024-02-13 14:12 UTC, parthdalaltech commented on src/lib/components/Transition/progress-bar/ProgressBar.svelte
> +    position: fixed;
check class from boostrap

2024-02-13 14:12 UTC, parthdalaltech commented on src/lib/components/Transition/progress-bar/ProgressBar.svelte
> +    flex-direction: column;
fd-c class from bootstrap

2024-02-13 14:12 UTC, parthdalaltech commented on src/lib/components/Transition/progress-bar/ProgressBar.svelte
> +    line-height: 18px;
check. bootstrap class

2024-02-14 06:38 UTC, itsmdasifraza commented on src/lib/components/Transition/progress-bar/ProgressBar.svelte
> +    position: fixed;
resolved

2024-02-14 06:38 UTC, itsmdasifraza commented on src/lib/components/Transition/progress-bar/ProgressBar.svelte
> +    position: fixed;
resolved

2024-02-14 06:39 UTC, itsmdasifraza commented on src/lib/components/Transition/progress-bar/ProgressBar.svelte
> +    flex-direction: column;
resolved

2024-02-14 06:40 UTC, itsmdasifraza commented on src/lib/components/Transition/progress-bar/ProgressBar.svelte
> +    line-height: 18px;
resolved

2024-02-14 06:47 UTC, parthdalaltech approved these changes

2024-02-14 06:48 UTC, parthdalaltech commented
approved

2024-02-14 06:48 UTC, merged

2024-03-01 18:49 UTC, punitkashyup commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/sparrowapp-dev/sparrow-app/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-03-01 19:17 UTC, punitkashyup commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/sparrowapp-dev/sparrow-app/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-03-01 19:44 UTC, punitkashyup commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/sparrowapp-dev/sparrow-app/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-03-07 12:06 UTC, punitkashyup commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/sparrowapp-dev/sparrow-app/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-03-08 07:21 UTC, punitkashyup commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/sparrowapp-dev/sparrow-app/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: