fix: home screen flickers while creating new workspace
sparrowapp-dev/sparrow-app pull request #317
Opened 2024-02-21 11:09 UTC by itsmdasifraza

## Description
fix home screen flickers while creating new workspace
Fixes issue #315 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build

## Have you tested locally?

- [ ] 👍 yes
- [ ] 🙅 no, because I am lazy

2024-02-21 13:26 UTC, parthdalaltech requested changes

2024-02-21 13:26 UTC, parthdalaltech commented on src/lib/components/header/header-dashboard/HeaderDashboard.ViewModel.ts
> +    if (response?.isSuccessful && response?.data?.data) {
destructure this beforehand and then use it in if statement like
const {isSuccessful,data} = response;

2024-02-21 13:26 UTC, parthdalaltech commented on src/lib/components/header/header-dashboard/HeaderDashboardDropdown.svelte
> +          id: workspace.name,
dont we have "id" key of workspace? coz i can see we are assigning id as the name key

2024-02-22 05:56 UTC, LordNayan approved these changes

2024-02-22 05:56 UTC, merged

2024-03-01 18:48 UTC, punitkashyup commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/sparrowapp-dev/sparrow-app/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-03-01 19:16 UTC, punitkashyup commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/sparrowapp-dev/sparrow-app/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-03-01 19:43 UTC, punitkashyup commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/sparrowapp-dev/sparrow-app/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-03-07 12:05 UTC, punitkashyup commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/sparrowapp-dev/sparrow-app/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-03-07 15:06 UTC, punitkashyup commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/sparrowapp-dev/sparrow-app/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-03-08 07:20 UTC, punitkashyup commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/sparrowapp-dev/sparrow-app/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: