feat: onboarding leave team, workspace navigation and management
sparrowapp-dev/sparrow-app pull request #62
Opened 2024-01-25 08:22 UTC by theanantchoubey

## Description
This PR adds the following features --:
1. Leave Team: Users apart from the owner will be able to leave the team.
2. Create New Workspace: On the "Create New Workspace" button click on the header dropdown, pop-up for creating a new workspace opens up.
3. Navigation: The user will be able to navigate along the workspaces of different teams
4. Teams UI and Teams Creation: The user will be able to create a team of his own with Drag and drop feature for uploading the logo of the team.

The following Bugs will be fixed in this PR --:
1. Duplicate Workspace Creation
2. RxDB Workspace and Teams Issues
3. UI issues

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/91460022/0c4b8093-1b95-4058-b67e-d27da9cfcbb8)

![image](https://github.com/sparrowapp-dev/sparrow-app/assets/91460022/5ac9a5fe-4045-438b-9e32-fb9717719480)

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build

## Have you tested locally?

- [x] 👍 yes
- [ ] 🙅 no, because I am lazy

## Any Known issue?
## Related Story, task & Documents?
438

2024-01-25 10:22 UTC, itsmdasifraza commented on src/lib/components/dropdown/ShowMore.svelte
> +                    : ""}>{item.displayText}</button
We have button component already that is used over the app. we can use that for getting aligned.

2024-01-25 10:25 UTC, itsmdasifraza commented on src/lib/components/table/all-workspace/AllWorkspace.svelte
> +                        )}
can we use === and enum here.

2024-01-25 10:26 UTC, itsmdasifraza commented on src/lib/components/Modal/CustomPopup.svelte
>      </div>
we can use button component here also

2024-01-25 10:28 UTC, itsmdasifraza commented on src/lib/components/dashboard/workspace-card-list/WorkspaceCardList.svelte
>                (item) =>
can we keep the logic and view separately

2024-01-25 10:31 UTC, itsmdasifraza commented on src/lib/components/dropdown/CustomDropdown.svelte
> +</script>
can we rename it something else rather than customDropdown, as reading the name it is not clear.

2024-01-25 10:32 UTC, itsmdasifraza commented on src/lib/components/dropdown/HeaderDropdown.svelte
Comments

2024-01-25 10:38 UTC, itsmdasifraza commented on src/lib/components/workspace/WorkspaceContent.svelte
> +                  style="font-size: 12px;"
button

2024-01-25 10:39 UTC, itsmdasifraza commented on src/lib/repositories/workspace.repository.ts
> +
comments

2024-01-25 12:00 UTC, LordNayan commented on src/lib/components/buttons/IconButton.svelte
> +  export let width: number = undefined;
We are declaring the variable as number type, yet assigning it undefined. This might cause problems.

2024-01-25 12:12 UTC, LordNayan requested changes
Just use proper data types and if you are sure about what data will come you can even skip writing types for variables.

for example -  let a = true will make "a" infer a boolean type automatically.

2024-01-26 07:16 UTC, itsmdasifraza commented on src/lib/components/workspace/WorkspaceContent.svelte
> +
TeamViewModel Object is already initiated at parent component, you can pass your methods wrapping in TeamServiceMethods or TeamRepositoryMethods as a props.

2024-01-26 07:36 UTC, merged

2024-02-13 12:36 UTC, punitkashyup commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/sparrowapp-dev/sparrow-app/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-13 14:10 UTC, punitkashyup commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/sparrowapp-dev/sparrow-app/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-13 14:58 UTC, punitkashyup commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/sparrowapp-dev/sparrow-app/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-15 13:05 UTC, punitkashyup commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/sparrowapp-dev/sparrow-app/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-15 18:53 UTC, punitkashyup commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/sparrowapp-dev/sparrow-app/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-19 10:43 UTC, punitkashyup commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/sparrowapp-dev/sparrow-app/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: