Refactor/collection list
sparrowapp-dev/sparrow-app pull request #747
Opened 2024-04-19 08:28 UTC by theketan26

## Description

Refactor: Collection list

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build

## Have you tested locally?

- [x] 👍 yes
- [ ] 🙅 no, because I am lazy

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md

## Any Known issue?
## Related Story, task & Documents?

2024-04-19 08:28 UTC, punitkashyup commented
Please attach the issue link

2024-04-19 10:46 UTC, Astitva877 commented on src/lib/components/collections/collections-list/import-curl/ImportCurl.viewModel.ts
>  }
If we have removed all methods from this file, and it doesn't serve any purpose so we can delete this file as well.

2024-04-19 10:50 UTC, Astitva877 commented on src/lib/components/collections/collections-list/searchTree/Request.svelte
> +  export let explorer: any;
We can make a interface to specify it's type, also we can change the name to something else which resonates to it's use.

2024-04-19 10:51 UTC, Astitva877 requested changes
@theketan26 comments are missing from various places, we can add comments for functions, imports to make the code more understandable.

2024-04-19 11:29 UTC, itsmdasifraza commented on src/pages/Collections/CollectionPage.ViewModel.ts
> +      userSource = {
pass workspaceId as  a parameter

2024-04-19 11:56 UTC, itsmdasifraza commented on src/pages/Collections/CollectionPage.ViewModel.ts
> +      id: UntrackedItems.UNTRACKED + uuidv4(),
get collection data from component as a props

2024-04-19 12:29 UTC, itsmdasifraza commented on src/pages/Collections/CollectionPage.ViewModel.ts
> +    let isValidClientJSON = false;
isImportDataLoading should be handled in UI file

2024-04-22 09:56 UTC, punitkashyup commented
Please attach the issue link

2024-04-23 17:01 UTC, itsmdasifraza commented on src/pages/Collections/CollectionPage.ViewModel.ts
> +   */
type not required in js-doc comment as we are already using typescript, same at multiple places

2024-04-25 20:11 UTC, itsmdasifraza commented on src/pages/Collections/CollectionsPage.svelte
>      <TabBar
set minSize as earlier

2024-04-25 20:11 UTC, itsmdasifraza commented on src/pages/Collections/CollectionsPage.svelte
>  >
local variable is not persistent here

2024-04-29 09:55 UTC, Astitva877 approved these changes

2024-04-29 09:56 UTC, merged

2024-06-07 16:46 UTC, pratikshinde590 commented
:tada: This PR is included in version 1.3.0 :tada:

The release is available on [GitHub release](https://github.com/sparrowapp-dev/sparrow-app/releases/tag/v1.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: