feat: Added shortcut button  [123]
sparrowapp-dev/sparrow-app pull request #878
Opened 2024-05-24 14:17 UTC by Abhishek9503

## Description

Added shortcut button in the collection page 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build

## Have you tested locally?

- [ ] 👍 yes
- [ ] 🙅 no, because I am lazy

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md

## Any Known issue?
## Related Story, task & Documents?

2024-05-24 14:18 UTC, punitkashyup commented
Please attach the issue link

2024-05-24 14:18 UTC, punitkashyup commented
Please attach the issue link

2024-05-24 14:40 UTC, itsmdasifraza requested changes

2024-05-24 14:40 UTC, itsmdasifraza commented on src/packages/@library/icons/FolderPlus.svelte
> +<path d="M13.3327 11.3333C13.3327 12.0687 12.7348 12.6667 11.9993 12.6667H3.99935C3.26393 12.6667 2.66602 12.0687 2.66602 11.3333V4.66666C2.66602 3.93124 3.26393 3.33333 3.99935 3.33333H6.66602C7.084
<script>
    export let height = "24px";
    export let width = "24px";
    export let color = "grey";
  </script>
  
add this script, and pass value as a props

2024-05-24 14:40 UTC, itsmdasifraza commented on src/packages/@workspaces/features/collection-list/components/collection/Collection.svelte
> +        </div>
pass color prop

2024-05-24 14:40 UTC, itsmdasifraza commented on src/packages/@workspaces/features/collection-list/components/collection/Collection.svelte
> +          </div>
pass height, width ,color prop here

2024-05-24 14:40 UTC, itsmdasifraza commented on src/packages/@workspaces/features/collection-list/components/collection/Collection.svelte
> +  }
use common class for both

2024-05-27 06:13 UTC, punitkashyup commented
Please attach the issue link

2024-05-27 06:23 UTC, punitkashyup commented
Please attach the issue link

2024-05-27 06:27 UTC, itsmdasifraza approved these changes

2024-05-27 06:37 UTC, merged